service: api-simulador-banco

frameworkVersion: "4"

plugins:
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs20.x # or your current node version
  region: ${opt:region, 'us-east-2'} # or your region
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
  timeout: 30
  profile: profile-dgo

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
